### ISSUE TITLE
Exporting RTF now exports no entries

### ISSUE THREAD

**Issue by crustamet** [AamuLumi/Rimworld-Diary#3]
![image](https://user-images.githubusercontent.com/36475250/203003433-bf13adae-cc44-4e43-87df-d8c92f6a442d.png)

The thing is i have loaded a save file and then export because you just updated and i wanted to see how it is working.
So for me this happens right now is this what needs to happen ?
My settings are **Prerender** : **ALL** and **Events** : **ALL**

**Comment by crustamet** [comment]
I only hope if i play another new game and 1 year goes by, when i export everything, I hope will not get blank days just like in the screen shot

**Comment by AamuLumi** [comment]
Unluckily, I can't do anything for the above reason except importing the current memory interactions (maybe I'll give it a try) and waiting for Tynan to implement a higher limit for interactions in vanilla Rimworld.

I'll take another look to Rimworld code to check if I'm wrong and all interactions are stored somewhere, but I'm almost sure what I've read is good.

**Comment by AamuLumi** [comment]
Something like auto-export each day can be done.

I misread [this message](https://github.com/AamuLumi/Rimworld-Diary/issues/3#issuecomment-1324837966). 
If you start and do your game with the diary mod (and auto-write enable), there will be no problem for the export.
Everything written in the diary is stored differently than social interactions and events. I never remove anything from the diary, so it should not be any blank in the export.

Just remember to keep write filter to "All", "Events" or "Chats", because I currently can't bring back these entries if you decide to enable the mod **after** these things occured.
